- name: Install dependencies
  apt:
    name: "{{packages}}"
    update_cache: yes
    state: present

- name: Download todo from Nexus
  get_url:
    url: http://172.31.12.183:8081/repository/todo/todo-1.0.1.zip
    dest: /root/todo
    username: admin
    password: kavya

- name: Unzip the Downloaded Content
  unarchive:
    src: /root/todo
    dest: /root
    remote_src: yes

- name: Copy todo.Service 
  copy:
    src: todo.service
    dest: /etc/systemd/system/todo.service
  
- name: Start todo Service 
  systemd:
    name: todo
    daemon_reload: yes
    state: started
    enabled: yes

