- name: Import NodeJS Common role
  include_role:
    name: common
    tasks_from: nodejs
- name: Install Node Exporter Prometheus Monitoring
  include_role:
    name: common
    tasks_from: node_exporter
