- name: Install dependencies
  apt:
    name: "{{packages}}"
    update_cache: yes
    state: present

- name: Download users from Nexus
  get_url:
    url: http://172.31.12.183:8081/repository/users/users-1.0.1.zip
    dest: /root/users
    username: admin
    password: kavya

- name: Unzip the Downloaded Content
  unarchive:
    src: /root/users
    dest: /root/
    remote_src: yes


- name: Copy users Service file
  copy:
    src: "users.service"
    dest: /etc/systemd/system/users.service

- name: Start users Service
  systemd:
    name: "users"
    daemon_reload: yes
    state: started
    enabled: yes
